### ISSUE TITLE
Can't use "model" as Fact name

### ISSUE THREAD

**Issue by smarttowel** [uavos/apx-gcs#9]
My fact Fact(parent, "model", ...) cause error:
`Property override: "parent" "model"`
I think, that technical, private properties should be hided from user at least by name, f.ex., `__model`.

**Comment by uavinda** [comment]
My idea was to hide children under `facts` property. How about that?

**Comment by uavinda** [comment]
This should count the JS lookup shortcuts, omitting redundant `.facts.`, where property does not exists. Or something similar. So that, f.ex. `apx.vehicles.current.mandala.cmd.pos.tecs` is still accessible, but `apx.vehicles.current.mission.facts.title` (aka mission title fact) is different from `apx.vehicles.current.mission.title` (i.e. mission fact title).

**Comment by smarttowel** [comment]
I don't understand what you mean. This issue just about warning, when I create fact with name "model".

**Comment by smarttowel** [comment]
What about rename Fact::model property to Fact::_model?

**Comment by uavinda** [comment]
Then, why not to have to change names for all other fact's properties to be prefixed by '_'?

**Comment by smarttowel** [comment]
I don't know, what is better solution. But rename all fact properties with '_' is not good.

**Comment by uavinda** [comment]
A fact's `model` property provides QAbstractListModel interface for the fact's children. Wouldn't it be better to consider `model` as a **reserved** fact name? Since every fact has such property. Along with other properties, like `title`, `default`, `value`, etc? Although, I agree, `model` is not as descriptive, as let's say `children`, we might consider to rename this property, what do you think?

**Comment by smarttowel** [comment]
Okay, lets define model and other properties as reserved. If user create Fact with reserved name, we will see message in console and fact shouldn't added to QObject's tree.
